
#-*- coding: utf-8 -*-
'''
  <auto-generated>
    This code was generated by a tool.
    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
  </auto-generated>
'''

from enum import Enum


class test_TestExcelBean1 :
    def __init__(self, _json_):
        self.x1 = _json_['x1']
        self.x2 = _json_['x2']
        self.x3 = _json_['x3']
        self.x4 = _json_['x4']

class DefineFromExcel2 :
    def __init__(self, _json_):
        self.id = _json_['id']
        self.name = _json_['name']
        self.desc = _json_['desc']
        self.count = _json_['count']

class AttributeTable :
    def __init__(self, _json_):
        self.id = _json_['id']
        self.name = _json_['name']
        self.Enable = _json_['Enable']
        self.Des = _json_['Des']
        self.Show = _json_['Show']
        self.DefaultValue = _json_['DefaultValue']
        self.ISFloat = _json_['ISFloat']
        self.End = _json_['End']
        self.CanShow = _json_['CanShow']


class test_TbDefineFromExcel2:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = DefineFromExcel2(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.id] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)

class cfg_TbAttribute:

    def __init__(self, _json_ ):
        self._dataMap = {}
        self._dataList = []
        
        for _json2_ in _json_:
            _v = AttributeTable(_json2_)
            self._dataList.append(_v)
            self._dataMap[_v.id] = _v

    def getDataMap(self) : return self._dataMap
    def getDataList(self) : return self._dataList

    def get(self, key) : return self._dataMap.get(key)



class cfg_Tables:
    def __init__(self, loader):
        self.TbDefineFromExcel2 = test_TbDefineFromExcel2(loader('test_tbdefinefromexcel2')); 
        self.TbAttribute = cfg_TbAttribute(loader('cfg_tbattribute')); 

